[server]
enableXsrfProtection = false
enableCORS = false

[theme]
base = "light"
primaryColor = "#1668A4"
backgroundColor = "#EEF2F7"
secondaryBackgroundColor = "#F6FAFB"
textColor = "#0B1424"
font = "sans serif"
