[server]
enableXsrfProtection = false
enableCORS = false

[theme]
base = "light"
primaryColor = "#1A6FA8"
backgroundColor = "#EEF4F9"
secondaryBackgroundColor = "#F4F8FB"
textColor = "#1A202C"
font = "sans serif"
